apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdres
  template:
    metadata:
      labels:
        app: sdres
    spec:
      containers:
      - image: okteto.dev/sdres:latest
        name: sdres
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "5eaf4aa3-2dc8-4219-9d51-c0ad18779433"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "e0bd6d7c-f805-4270-8dac-b830a603f86b"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
