apiVersion: apps/v1
kind: Deployment
metadata:
  name: brdes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brdes
  template:
    metadata:
      labels:
        app: brdes
    spec:
      containers:
      - image: okteto.dev/brdes:latest
        name:brdes
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "04e2ff74-93f5-11ec-b909-0242ac120002"
        - name: Vless_Path
          value: "/desw"
        - name: Vmess_UUID
          value: "19be46ec-93f5-11ec-b909-0242ac120002"
        - name: Vmess_Path
          value: "/mdres"
        - name: Share_Path
          value: "/sdewo"
