apiVersion: apps/v1
kind: Deployment
metadata:
  name: grdesa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grdesa
  template:
    metadata:
      labels:
        app: grdesa
    spec:
      containers:
      - image: okteto.dev/grdesa:latest
        name: grdesa
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "618b6edd-07ac-412e-92c7-ee1fe1d31e72"
        - name: Vless_Path
          value: "/mjhuy"
        - name: Vmess_UUID
          value: "174537f8-93f1-11ec-b909-0242ac120002"
        - name: Vmess_Path
          value: "/gtfr"
        - name: Share_Path
          value: "/pgytf"
